/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package akrent;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andin
 */
public class Jaminan extends javax.swing.JFrame {

    /**
     * Creates new form Jaminan
     */
    private DefaultTableModel model;
    public Jaminan() {
        initComponents();
        scaleImage();
        scaleImage1();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        model = new DefaultTableModel();
        
        TabelJaminan.setModel(model);
        model.addColumn("ID Jaminan");
        model.addColumn("Jenis Jaminan");
        model.addColumn("Unit");
        loadData();
    }
    
    private void scaleImage(){
        ImageIcon icon = new ImageIcon((getClass().getResource("/car.png")));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaledIcon);
    }
    private void scaleImage1(){
        ImageIcon icon = new ImageIcon((getClass().getResource("/icon_assurance.png")));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel5.setIcon(scaledIcon);
    }
    
    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        model.setRowCount(0);

        try {
            Connection c = KoneksiDatabase.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM jaminan;";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[3];
                o[0] = r.getInt("id_jaminan");
                o[1] = r.getString("jenis_jaminan");
                o[2] = r.getInt("unit");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJaminan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputJaminan = new javax.swing.JTextField();
        inputUnit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deleteMobil = new javax.swing.JButton();
        editMobil = new javax.swing.JButton();
        SubmitMobil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Beranda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("car");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(871, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TabelJaminan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelJaminan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelJaminanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelJaminan);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel3.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jenis Jaminan");

        inputJaminan.setForeground(new java.awt.Color(102, 102, 102));
        inputJaminan.setText("Masukkan Jenis Jaminan");
        inputJaminan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputJaminanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputJaminanFocusLost(evt);
            }
        });

        inputUnit.setForeground(new java.awt.Color(102, 102, 102));
        inputUnit.setText("Masukkan Unit");
        inputUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUnitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUnitFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Unit");

        deleteMobil.setText("Delete");
        deleteMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMobilActionPerformed(evt);
            }
        });

        editMobil.setText("Edit");
        editMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMobilActionPerformed(evt);
            }
        });

        SubmitMobil.setText("Submit");
        SubmitMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitMobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editMobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubmitMobil))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputJaminan, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(inputUnit))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputJaminan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMobil)
                    .addComponent(editMobil)
                    .addComponent(SubmitMobil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Jaminan");

        jLabel8.setText("© Kelompok 1. All rights reserved.");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(343, 343, 343))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputUnitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUnitFocusGained
        // TODO add your handling code here:
        if (inputUnit.getText().equals("Masukkan Unit")) {
            inputUnit.setText("");
            inputUnit.setForeground(new Color (0,0,0));
        }
    }//GEN-LAST:event_inputUnitFocusGained

    private void inputUnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUnitFocusLost
        // TODO add your handling code here:
        if (inputUnit.getText().equals("")) {
            inputUnit.setText("Masukkan Unit");
            inputUnit.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_inputUnitFocusLost

    private void inputJaminanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputJaminanFocusLost
        // TODO add your handling code here:
        if (inputJaminan.getText().equals("")) {
            inputJaminan.setText("Masukkan Jenis Jaminan");
            inputJaminan.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_inputJaminanFocusLost

    private void inputJaminanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputJaminanFocusGained
        // TODO add your handling code here:
        if (inputJaminan.getText().equals("Masukkan Jenis Jaminan")) {
            inputJaminan.setText("");
            inputJaminan.setForeground(new Color (0,0,0));
        }
    }//GEN-LAST:event_inputJaminanFocusGained

    private void SubmitMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitMobilActionPerformed
        // TODO add your handling code here:
        if (inputJaminan.getText().equals("Masukkan Jenis Jaminan") || inputUnit.getText().equals("Masukkan Unit")) {
            jLabel7.setForeground(Color.red);
            jLabel7.setText("Error, Pastikan anda memasukkan Semua data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            return;
        }
        String jaminan = inputJaminan.getText();
        String unit = inputUnit.getText();
        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "INSERT INTO jaminan (jenis_jaminan, unit) VALUES (?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, jaminan);
            p.setString(2, unit);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error: " + e.getMessage());
        } finally {
            loadData(); // Reload data after insertion
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Succes, Telah memasukkan data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            inputJaminan.setText("Masukkan Jenis Jaminan");
            inputJaminan.setForeground(new Color (102,102,102));
            inputUnit.setText("Masukkan Unit");
            inputUnit.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_SubmitMobilActionPerformed

    private void editMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMobilActionPerformed
        // TODO add your handling code here:
        int i = TabelJaminan.getSelectedRow();
        if (i == -1) {
            // tak ada baris terseleksi
            jLabel7.setForeground(Color.red);
            jLabel7.setText("Error, Pastikan anda memilih data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            return;
        }
        String id = model.getValueAt(i, 0).toString();
        String jaminan = inputJaminan.getText();
        String unit = inputUnit.getText();
        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "UPDATE jaminan SET jenis_jaminan = ?, unit = ? WHERE id_jaminan = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, jaminan);
            p.setString(2, unit);
            p.setString(3, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error: " + e.getMessage());
        } finally {
            loadData(); // Reload data after insertion
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Succes, Telah mengedit data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            inputJaminan.setText("Masukkan Jenis Jaminan");
            inputJaminan.setForeground(new Color (102,102,102));
            inputUnit.setText("Masukkan Unit");
            inputUnit.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_editMobilActionPerformed

    private void deleteMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMobilActionPerformed
        // TODO add your handling code here:
        int i = TabelJaminan.getSelectedRow();
        if (i == -1) {
            jLabel7.setForeground(Color.red);
            jLabel7.setText("Error, Pastikan anda memilih data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            return;
        }
        String id = model.getValueAt(i, 0).toString();
        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "DELETE FROM jaminan WHERE id_jaminan = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println("Terjadi Error");
        } finally {
            loadData();
            jLabel7.setForeground(Color.green);
            jLabel7.setText("Succes, Telah menghapus data");
            
            javax.swing.Timer timer = new javax.swing.Timer(5000, e -> {
                jLabel7.setText(""); // Clear the error message
            });
            timer.setRepeats(false); // Ensure the timer runs only once
            timer.start();
            inputJaminan.setText("Masukkan Jenis Jaminan");
            inputJaminan.setForeground(new Color (102,102,102));
            inputUnit.setText("Masukkan Unit");
            inputUnit.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_deleteMobilActionPerformed

    private void TabelJaminanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelJaminanMouseClicked
        // TODO add your handling code here:
        int i = TabelJaminan.getSelectedRow();
        if (i == -1) {
            // tak ada baris terseleksi
            return;
        }
        
        String jaminan = model.getValueAt(i, 1).toString();
        inputJaminan.setForeground(new Color(0,0,0));
        inputJaminan.setText(jaminan);
        
        String unit = model.getValueAt(i, 2).toString();
        inputUnit.setForeground(new Color(0,0,0));
        inputUnit.setText(unit);
    }//GEN-LAST:event_TabelJaminanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jaminan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jaminan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitMobil;
    private javax.swing.JTable TabelJaminan;
    private javax.swing.JButton deleteMobil;
    private javax.swing.JButton editMobil;
    private javax.swing.JTextField inputJaminan;
    private javax.swing.JTextField inputUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
